### PR TITLE
Encrypted/Secure Room with SafeRoom

### PR DESCRIPTION
**Pull request by hannesa2**
I don't know what the best approach is to force encryption for Room. So I create this PR to show the maintainer(s) of this repo how a possible way could look like, or to keep attention on encryption.
I know this is not merge-able, but maybe I help to force encryption for Room

To make it short: we want encryption for Room !

### CODE REVIEW

**Comment by originx** [comment]
Lovely out of the box encryption supported from room natively would be great!

**Comment by hannesa2** [comment]
Here is a Google issue for this too https://issuetracker.google.com/issues/112806418

**Comment by hannesa2** [comment]
Maven https://s3.amazonaws.com/repo.commonsware.com is not trust full, I run into serious issues with version `0.5.1`, it migrates pragma and version `1.0.0` reverted it.
But code has nothing of this included, so it seams artifacts and code does not fit, and was build on a local machine

So I made a fork with a deterministic build ! 
Who is interested in security should ask to whom you trust ! Public is better then private

https://github.com/hannesa2/cwac-saferoom/pull/2
https://jitpack.io/#hannesa2/cwac-saferoom

**Comment by dazza5000** [comment]
Maybe we could make this part of the wiki / README.md?

**Comment by hannesa2** [comment]
I can not recommend https://github.com/commonsguy/cwac-saferoom for production. The company, I work for, removed this lib <= v1.0.1 because there were a lot of unexplainable, corrupted databases (with stable password) observed in Crashlytics.
Arrount 1 % of all sessions, it sounds not much, but when you have millions of installations, then it's too much !

We were never able to reproduce it in development, so we decided to remove it.

**Pull request closed without merging**
