### PR TITLE
Fix tools:context

### PR DESCRIPTION
**Pull request by STAR-ZERO**

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
Thanks!

nit: can you remove the stars from the commit message?

**Comment by STAR-ZERO** [comment]
What is the `stars`? My icon?

**Comment by JoseAlcerreca** [comment]
Yeah, it might get confusing.

**Comment by STAR-ZERO** [comment]
The stars is not included in commit message.

**Comment by JoseAlcerreca** [comment]
LOL I thought it was an emoji

**Pull request merged**
