### PR TITLE
Update Gradle wrapper to 4.1

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the Gradle wrapper of all three sample projects to the latest version `4.1`. The files were *autogenerated* by the `wrapper` task, which is why the `gradlew` shell scripts are now at the latest version as well.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Updated to `4.0-rc-1` - Amended commit and rebased.

**Comment by friederbluemle** [comment]
Updated to `4.0-rc-2` - Commit amended again and force pushed.
@yigit Could you have a look? Thanks.

**Comment by friederbluemle** [comment]
Updated again to `4.0-rc3`

**Comment by friederbluemle** [comment]
[Gradle 4.0](https://github.com/gradle/gradle/releases/tag/v4.0.0) is out now! I amended the commit for this latest, stable version.

**Comment by friederbluemle** [comment]
Rebased again, and also included the wrapper found in the newly added `BasicRxJavaSample` folder in the commit.

**Comment by friederbluemle** [comment]
Rebased again, and updated to the latest stable version `4.1`

**Comment by JoseAlcerreca** [comment]
Many thanks! I have to close this though, since we have be the ones to bump the versions.

**Comment by friederbluemle** [comment]
Hmm okay. Would you mind explaining why? This is an open source project isn't it?

**Pull request closed without merging**
