### PR TITLE
Adds Navigation advanced sample

### PR DESCRIPTION
**Pull request by JoseAlcerreca**
Android Architecture Components Advanced Navigation Sample
==============================================

### Features

This sample showcases the behavior of a bottom navigation view following the [Principles or
Navigation](https://developer.android.com/topic/libraries/architecture/navigation#fixed).

 * Fixed start destination
 * Navigation state should be represented via a stack of destinations
 * The Up button never exits your app
 * Up and Back are identical within your app's task
 * Deep linking and navigating to a destination should yield the same stack

Check out the
[UI tests](https://github.com/googlesamples/android-architecture-components/tree/master/NavigationAdvancedSample/app/src/androidTest/java/com/example/android/navigationadvancedsample/BotomNavigatoinTest.kt)
to learn about specific scenarios.

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
Added #571 to deal with the flaky test.

**Comment by NitroG42** [comment]
I think the sample miss a use case (or maybe it is for another sample):
What about the case where your app contains a Bottom Navigation View, like this Advanced Sample, but before the home screen is a  "SplashFragment" with no BNV.

In the same way, if there is a About button in the toolbar of the home screen, that must display the fragment in fullscreen without the BNV. 

What is the recommanded way to do this ? use multiple Activity ? use a single Activity but hide Activity component like the BNV on specifics destination ? 

I tried to put a NavHostFragment inside a HomeFragment (which would contains the BottomNavigationBar), but it doesn't seem to work that way (maybe I just missed how to use a fragment as a NavHost).

I really think that's a use case that lots of people have, so I hope you can provide some answer in a remote future about this.
Thank you !

**Comment by pkoutsovasilis** [comment]
There is something wrong with how different options menus for different fragments are handled. Specifically, the options menu for fragments inside the same graph are working fine, but when lets say you go to another graph by pressing the bottom nav, it holds the options menu from the previous one. This in conjuction with the previous comment IMHO make this sample not suitable for the daily needs of android development.

**Comment by jonandersen** [comment]
@pkoutsovasilis I noticed that happened as well, I solved it by invalidating the menu on each fragment change

```
   controller.observe(this, Observer { navController ->
            setupActionBarWithNavController(navController)
            invalidateOptionsMenu()
        })
```

**Comment by ianhanniballake** [comment]
The correct answer is to upgrade to [Fragments 1.1.0-alpha09](https://developer.android.com/jetpack/androidx/releases/fragment#1.1.0-alpha09) or higher as the [underlying issue](https://issuetracker.google.com/issues/131581013) is now fixed.

**Pull request merged**
