### PR TITLE
Bugfix/666 code style and fix broken instrumentation tests

### PR DESCRIPTION
**Pull request by RodrigoMirandaMarenco**

### CODE REVIEW

**Comment by dlam** [comment]
I'm not sure these are all changes that we want - at the very least we want to continue using AndroidX test's `ApplicationProvider` over `InstrumentationRegistry`

**Comment by RodrigoMirandaMarenco** [comment]
@dlam I see what happened, I had to run the update_versions script to import androidx.test.core.app.ApplicationProvider, I'll update the PR with the changes 😅

**Comment by RodrigoMirandaMarenco** [comment]
@dlam PR updated

**Comment by JoseAlcerreca** [comment]
Hi Rodrigo, many thanks for your PR. I'm going to close it because it does not adhere to the code style used in this project.

I would recommend you to send one PR per change so it's easier to review.

**Comment by RodrigoMirandaMarenco** [comment]
Got it! 😅 Thanks @JoseAlcerreca ! I'll keep that in mind when contributing in the future.

**Pull request closed without merging**
