### PR TITLE
Deprecated API are replaced

### PR DESCRIPTION
**Pull request by zakharovsergey1000**
Deprecated InstrumentationRegistry.getContext() and InstrumentationRegistry.getTargetContext() are replaced with ApplicationProvider.getApplicationContext()

### CODE REVIEW

**Comment by zakharovsergey1000** [comment]
I signed it!

**Comment by dlam** [comment]
@zakharovsergey1000 I believe you may need to correct the commit author in order for googlebot to recognize CLA status.

Check the "Individual Signers" section in googlebot's message above.

Make sure your git commit author name and email are set correctly:
```
git config --global user.name "Foo Bar"
git config --global user.email "foo@example.com"
```

And then you can `git commit --amend --author"Foo Bar<foo@example.com>"` to edit the author of your last commit.

**Comment by dlam** [comment]
Thanks for helping with sample cleanup @zakharovsergey1000  :slightly_smiling_face:

**Comment by zakharovsergey1000** [comment]
I'm glad to help!

**Pull request merged**
