### PR TITLE
Migration test

### PR DESCRIPTION
**Pull request by umitems**
Add an example for database migration test. @JoseAlcerreca This is my first PR please give me a recommend. I also found something wrong at https://developer.android.com/topic/libraries/architecture/room.html#db-exporting-schema how can it fix it?

### CODE REVIEW

**Comment by umitems** [comment]
@googlebot  I have signed

**Comment by umitems** [comment]
@googlebot I have signed

**Comment by JoseAlcerreca** [comment]
Hey umitems, thanks for the awesome PR!

However we already published a sample on migrations to keep the other project's code simpler, so I'm closing this one.

Thanks!

**Comment by umitems** [comment]
ok, so sad T^T

**Comment by florina-muntenescu** [comment]
@umitems - You mentioned that you found something wrong in the [documentation](https://developer.android.com/topic/libraries/architecture/room.html#db-exporting-schema). Could you please create an issue on the [official issue tracker](https://issuetracker.google.com), please.

**Comment by umitems** [comment]
@florina-muntenescu which component should I use to create the issue?

**Pull request closed without merging**
