### PR TITLE
Benchmark library version is updated

### PR DESCRIPTION
**Pull request by zakharovsergey1000**

### CODE REVIEW

**Comment by zakharovsergey1000** [comment]
@googlebot I fixed it.

**Comment by dlam** [comment]
There's actually a `versions.gradle` file in the base folder of the repo - could you move your change there and then run `./update_versions.sh`?

**Comment by zakharovsergey1000** [comment]
Done

**Comment by dlam** [comment]
Thank you! Could you also put the kotlin version bump into the common versions.gradle file or undo it?

**Comment by zakharovsergey1000** [comment]
Done

**Comment by dlam** [comment]
Thanks for contributing !

**Pull request merged**
